# -*- coding: utf-8 -*-
"""For_loop_Break.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHi0TSPtIQQl6E_0iY2IPCC0r4CZzFwP

# Task 1: print number from1 to 5
"""

print("Task 1:")
for i in range(1,6):
    print(i)

"""# Task 2: print odd number from 1 to 10"""

print("\nTask 2:")
for i in range(1,11, 2):
    print(i)

"""# Task 3: Nested loop pattern"""

print("\nTask 3:")
for i in range(3):        # 0,1,2
    for j in range(2):  # 0,1
        print(i, j)

"""# Task 4: Break when number is 5"""

print("\nTask 4:")
for i in range(1,8):
    if i == 5:
        break
    print(i)