# -*- coding: utf-8 -*-
"""python_basic_anil_kumar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iizY6KMREFDVceUhvcpr1BJm7EVxfKT0

Task 1:Variables and dara types
"""

name = "O Anil Kumar"
age = 27
height = 1.71
is_student = True

#Print all values in a single statement
print(name, age, height, is_student)

"""Task 2: Sring Formatting

"""

print(f"{name} | Age: {age} | height:{height} | Student: {is_student}")

"""Task 3: Arthmetic Operations"""

age_in_months = age*12
age_in_days = age*365
remainder = age % 7
age_square = age**2

print("\n--- Age Calculations---")
print("Age in number", age_in_months)
print("Age in days", age_in_days)
print("Remainder when age is divided by 7:", remainder)
print("Square of age", age_square)